version: "3.9"

services:
    postgres:
        container_name: database
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
