service: projeto-books
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "cognito-idp:AdminInitiateAuth"
            - "cognito-idp:AdminConfirmSignUp"
          Resource: !GetAtt MyUserPool.Arn
        - Effect: Allow
          Action:
            - "cognito-idp:SignUp"
          Resource: "*"

package:
  individually: true

resources:
  Resources:
    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: authorizer-test
        UsernameAttributes: 
          - 'email'
        AutoVerifiedAttributes:
          - 'email'
        UsernameConfiguration:
          CaseSensitive: false

    MyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: authorizer-books
        UserPoolId: !Ref MyUserPool
        GenerateSecret: true
        AllowedOAuthFlowsUserPoolClient: false
        ExplicitAuthFlows:
          - "ALLOW_ADMIN_USER_PASSWORD_AUTH"
          - "ALLOW_REFRESH_TOKEN_AUTH"

functions:
  lambda-proxy:
    name: projeto-lambda-proxy
    handler: dist/src/index.handler
    package:
      exclude:
        - "./**"
      include:
        - "node_modules/**"
        - "dist/**"
    events:
      - http:
          path: /{proxy+}
          method: ANY
          authorizer:
            name: cognito-authorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - MyUserPool
                - Arn
